openapi: 3.0.0
info:
  title: Satellite Spotter API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: 開発用ローカルサーバー
paths: # エンドポイント
  /api/v1/locations:
    get:
      summary: 検索クエリに対応する場所の代表座標を検索する．
      parameters:
        - name: q
          in: query
          required: true
          description: 検索したい市区町村名
          schema:
            type: string
        - name: lat
          in: query
          required: true
          description: マップにおける視点の緯度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Latitude'
        - name: lon
          in: query
          required: true
          description: マップにおける視点の経度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Longitude'
      responses:
        '200':
          description: 成功時のレスポンス（0件の場合は空の配列を返す．）
          content:
            application/json:
              schema:
                type: array # 使用するのは1件のみだが，検索結果は全て正確に提供する．
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: 場所の名称
                      example: "北海道札幌市中央区旭ケ丘一丁目"
                    lat:
                      type: number
                      description: 緯度（十進法度単位）
                      example: 34.391303
                    lon:
                      type: number
                      description: 経度（十進法度単位）
                      example: 132.45211
        '400':
          description: クエリパラメータが不正な場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部で予期せぬエラーが発生した場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/spots: # /apiで通常のページと区別する．/v1でバージョンを管理する．
    get: # データの取得
      summary: 観測スポット候補を検索する．
      parameters:
        - name: lat # パラメータ名
          in: query # URLの末尾に付与されるクエリパラメータに指定
          required: true # このパラメータは必須
          description: 探索中心の緯度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Latitude'
        - name: lon
          in: query
          required: true
          description: 探索中心の経度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Longitude'
        - name: radius
          in: query
          required: true
          description: 探索半径（km）
          schema:
            type: integer
            default: 30
            minimum: 1
            maximum: 125
        - name: limit # ページネーション用
          in: query
          required: false
          description: 取得するスポットの最大数
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: offset # ページネーション用
          in: query
          required: false
          description: 取得を開始する位置
          schema:
            type: integer
            default: 0
            minimum: 0
      responses: # URL（リソース）そのものは必ず存在するため，'404'は無し．
        '200': # OK
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: ヒットしたスポットの総数（ページネーション用）
                    example: 42
                  spots:
                    type: array
                    items:
                      type: object
                      properties:
                        spot_id:
                          type: string
                          description: スポットを一意に識別するID
                          example: 1910014046
                        name:
                          type: string
                          example: 鏡山公園
                        lat:
                          type: number
                          description: 緯度（十進法度単位）
                        lon:
                          type: number
                          description: 経度（十進法度単位）
        '400': # Bad Request（クライアントのミス）
          description: パラメータが不正な場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': # Internal Server Error（サーバーのミス）
          description: サーバー内部で予期せぬエラーが発生した場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/events:
    get:
      summary: 特定の座標で見える観測イベントのリストを取得する．
      parameters:
        - name: lat
          in: query
          required: true
          description: 緯度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Latitude'
        - name: lon
          in: query
          required: true
          description: 経度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Longitude'
      responses:
        '200':
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        start_time:
                          type: string
                          format: date-time
                          description: イベントの開始時刻（ISO 8601）
                          example: "2025-10-11T19:50:45+09:00"
                        visibility:
                          type: number
                          description: 最終的な可視性スコア
                          example: 0.8
                          minimum: 0.0
                          maximum: 1.0
                        event_type:
                          type: string
                          description: 観測対象のタイプ（ISS, Starlink Satellite Train, etc.）
                          example: "Starlink Satellite Train"
                        international_designators:
                          type: array
                          items:
                            type: string
                            description: 詳細表示の際に衛星を一意に識別するための国際衛星識別符号
                          example: ["2025-223A", "2025-223B", "2025-223C", "2025-223D", "2025-223E"]
        '400': # Bad Request（クライアントのミス）
          description: パラメータが不正な場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': # Internal Server Error（サーバーのミス）
          description: サーバー内部で予期せぬエラーが発生した場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/trajectories:
    get:
      summary: 特定のイベントの軌道とスコア詳細を取得する．
      parameters:
        - name: lat
          in: query
          required: true
          description: 緯度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Latitude'
        - name: lon
          in: query
          required: true
          description: 経度（十進法度単位）
          schema:
            $ref: '#/components/schemas/Longitude'
        - name: start_time
          in: query
          required: true
          description: イベントの開始時刻（ISO 8601）
          schema:
            type: string
            format: date-time
            example: "2025-10-11T19:50:45+09:00"
        - name: international_designators
          in: query
          required: true
          description: 開始時間と終了時間の決定に必要となる注目している衛星の国際衛星識別符号
          schema:
            type: array
            items:
              type: string
          style: form # URLのクエリ文字列形式で表現
          explode: false # 複数値はカンマ区切り
          example: ["2025-223A", "2025-223B", "2025-223C", "2025-223D", "2025-223E"]
      responses:
        '200':
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  start_time:
                    type: string
                    format: date-time
                    description: イベントの開始時刻（ISO 8601）
                    example: "2025-10-11T19:50:45+09:00"
                  end_time:
                    type: string
                    format: date-time
                    description: イベントの終了時刻（ISO 8601）
                    example: "2025-10-11T19:55:45+09:00"
                  trajectories:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                          example: "2025-10-11T19:50:45+09:00"
                        positions:
                          type: array
                          description: 当該時刻における全衛星の位置リスト
                          items:
                            type: object
                            properties:
                              international_designator:
                                type: string
                                example: "2025-223A"
                                description: 国際衛星識別番号
                              ra:
                                type: number
                                format: float
                                description: 当該衛星の赤経（度）
                              dec:
                                type: number
                                format: float
                                description: 当該衛星の赤緯（度）
                  scores:
                    type: object
                    properties:
                      visibility:
                        type: number
                        description: 最終的な可視性スコア
                        example: 0.8
                        minimum: 0.0
                        maximum: 1.0
                      topography:
                        type: number
                        description: 地形スコア
                        example: 0.8
                        minimum: 0.0
                        maximum: 1.0
                      sky_glow:
                        type: number
                        description: 光害スコア
                        example: 0.8
                        minimum: 0.0
                        maximum: 1.0
                      rain:
                        type: number
                        description: 雨スコア
                        example: 0.8
                        minimum: 0.0
                        maximum: 1.0
                      cloud:
                        type: number
                        description: 雲量スコア
                        example: 0.8
                        minimum: 0.0
                        maximum: 1.0
                      met_visibility:
                        type: number
                        description: 気象学的な視程スコア
                        example: 0.8
                        minimum: 0.0
                        maximum: 1.0
        '400': # Bad Request（クライアントのミス）
          description: パラメータが不正な場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500': # Internal Server Error（サーバーのミス）
          description: サーバー内部で予期せぬエラーが発生した場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Latitude: # 緯度のスキーマ
      type: number
      format: float
      minimum: -90.0
      maximum: 90.0
    Longitude: # 経度のスキーマ
      type: number
      format: float
      minimum: -180.0
      maximum: 180.0
    ErrorResponse: # 共通のエラーレスポンスを定義（DRY原則に基づき）
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
      example:
        error:
          code: "INVALID_PARAMETER"
          message: "lat（緯度）は，-90から90の間で指定してください．"
