"""Change sky_glow_score to sqm_value in spots table.

Revision ID: 0b0716919653
Revises: 84975df10640
Create Date: 2025-10-17 22:13:25.778334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0716919653'
down_revision: Union[str, Sequence[str], None] = '84975df10640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('sqm_value', sa.Float(), nullable=True))
    op.drop_column('spots', 'sky_glow_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('sky_glow_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('spots', 'sqm_value')
    # ### end Alembic commands ###
