"""Rename sqm_value to wa2015_raw_value in spots table.

Revision ID: 586d8e9939ad
Revises: 0b0716919653
Create Date: 2025-10-20 22:31:24.035473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586d8e9939ad'
down_revision: Union[str, Sequence[str], None] = '0b0716919653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('wa2015_raw_value', sa.Float(), nullable=True))
    op.drop_column('spots', 'sqm_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('sqm_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('spots', 'wa2015_raw_value')
    # ### end Alembic commands ###
