"""delete osm_tag

Revision ID: 63a2a07b7aab
Revises: f6fca0f86f64
Create Date: 2025-10-13 19:41:51.252657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a2a07b7aab'
down_revision: Union[str, Sequence[str], None] = 'f6fca0f86f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'osm_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('osm_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
