"""Add column elevation_m to spots table

Revision ID: 84975df10640
Revises: 5eebb6280d01
Create Date: 2025-10-17 09:04:16.775540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84975df10640'
down_revision: Union[str, Sequence[str], None] = '5eebb6280d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('elevation_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'elevation_m')
    # ### end Alembic commands ###
