"""Change lat lon to geom in locations table

Revision ID: e978c1a3828f
Revises: 1088b9ad21fc
Create Date: 2025-10-14 01:44:10.425657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e978c1a3828f'
down_revision: Union[str, Sequence[str], None] = '1088b9ad21fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.drop_column('locations', 'lon')
    op.drop_column('locations', 'lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('locations', 'geom')
    # ### end Alembic commands ###
